### ISSUE TITLE
Authentication Parameter

### ISSUE THREAD

**Issue by quanngo301** [jburkhardt/RCriteo#11]
Where can I find the info of parameters from this request in Criteo?

I would assume "userName" as email address I use to register as the an API user, "companyName" as the account name, but dont know where to get "appName"

authToken <- doCriteoAuth(user = "userName", password = "**********", company = "companyName", app = "appName", version = "3.6"

**Comment by jburkhardt** [comment]
You can provide any values for ```appName``` and ```companyName```. The arguments just have to be set with any random value. Read here #2

**Comment by quanngo301** [comment]
It works. Thanks!

Btw, is there any workaround to add campaignName as extra dimension beside campaignID in the final data sheet?

**Comment by jburkhardt** [comment]
Great!
I have to further investigate the API concerning the campaign names as an attribute.
