### ISSUE TITLE
appName

### ISSUE THREAD

**Issue by D-sizzle** [jburkhardt/RCriteo#2]
Could you more clearly define appName for the app variable? And where can I find it? Also, is this still functioning? I see there hasnt been any contributions for a while.

**Comment by jburkhardt** [comment]
The package is functioning and in productive usage!
I think Criteo has to create an API access for you. If you have this already, you will find the ```appName``` in the criteo accout settings.
```doCriteoAuth```returns an ```authToken```. Furthermore you will need an ```appToken``` which you can get from your Criteo Account Manager.
Hope this helps!

**Comment by jburkhardt** [comment]
Update:
I just figured out that you can provide any text for ```appName``` and ```companyName```. The arguments just have to be set with any value.
