### ISSUE TITLE
AppName in AuthToken call

### ISSUE THREAD

**Issue by ChadEfaw** [jburkhardt/RCriteo#9]
Hello! 

I am looking to pull criteo data into R using your library. One snag I seem to have run into is the "AppName" section of the AuthToken call. Is the "AppName" the long string API Key? Is it a dedicated app like how Twitter uses their API? 

Thank you for your library, your work and your time! 

Chad

**Comment by jburkhardt** [comment]
```AppName``` can be any value. Read here:
https://github.com/jburkhardt/RCriteo/issues/2
